# Generated by Django 2.2.6 on 2020-06-30 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CAT', 'КОШКА'), ('DOG', 'СОБАКА'), ('PAR', 'ПОПУГАЙ')], default='DOG', max_length=3, verbose_name='Вид')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Описание')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_shelter.Breed', verbose_name='Порода')),
                ('kind', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='p_shelter.Kind', verbose_name='Вид животного')),
            ],
        ),
    ]
