# Generated by Django 2.2.6 on 2020-06-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='code',
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(choices=[('CAT', 'КОШКА'), ('DOG', 'СОБАКА'), ('PAR', 'ПОПУГАЙ')], default='DOG', max_length=3, verbose_name='Вид животного'),
        ),
    ]
