# Generated by Django 2.2.6 on 2020-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_shelter', '0002_auto_20200630_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
