# Generated by Django 2.2.6 on 2020-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_shelter', '0004_auto_20200630_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(choices=[('СОБАКА', 'СОБАКА'), ('КОШКА', 'КОШКА'), ('ПОПУГАЙ', 'ПОПУГАЙ')], default='СОБАКА', max_length=10),
        ),
    ]
