# Generated by Django 2.2.6 on 2020-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_shelter', '0005_auto_20200630_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='animals_photo/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
